# Generated by Django 5.2.5 on 2025-09-02 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StockPrice",
        ),
    ]
