# Generated by Django 5.2.5 on 2025-09-02 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("warehouse", "0002_delete_stockprice"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateDim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("year", models.IntegerField()),
                ("quarter", models.IntegerField()),
                ("month", models.IntegerField()),
                ("day", models.IntegerField()),
                ("day_of_week", models.IntegerField()),
                ("is_weekend", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "dim_date",
            },
        ),
        migrations.CreateModel(
            name="EconomicIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
            ],
            options={
                "db_table": "dim_econ_indicator",
            },
        ),
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "dim_exchange",
            },
        ),
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "dim_sector",
            },
        ),
        migrations.CreateModel(
            name="Symbol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=24)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                ("currency", models.CharField(blank=True, default="USD", max_length=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "exchange",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.exchange",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="warehouse.sector",
                    ),
                ),
            ],
            options={
                "db_table": "dim_symbol",
            },
        ),
        migrations.CreateModel(
            name="PriceDailyFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "open",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "high",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "low",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "close",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                (
                    "adj_close",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=18, null=True
                    ),
                ),
                ("volume", models.BigIntegerField(null=True)),
                ("source", models.CharField(default="yahoo", max_length=32)),
                ("load_ts", models.DateTimeField(auto_now_add=True)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.datedim",
                    ),
                ),
                (
                    "symbol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.symbol",
                    ),
                ),
            ],
            options={
                "db_table": "fact_price_daily",
            },
        ),
        migrations.CreateModel(
            name="EconDailyFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=6, max_digits=18, null=True),
                ),
                ("source", models.CharField(default="fred", max_length=32)),
                ("load_ts", models.DateTimeField(auto_now_add=True)),
                (
                    "date",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="warehouse.datedim",
                    ),
                ),
                (
                    "indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.economicindicator",
                    ),
                ),
            ],
            options={
                "db_table": "fact_econ_daily",
                "indexes": [
                    models.Index(
                        fields=["indicator", "date"],
                        name="fact_econ_d_indicat_487c5b_idx",
                    ),
                    models.Index(
                        fields=["date"], name="fact_econ_d_date_id_260be1_idx"
                    ),
                ],
                "unique_together": {("indicator", "date")},
            },
        ),
        migrations.AddIndex(
            model_name="symbol",
            index=models.Index(fields=["ticker"], name="dim_symbol_ticker_064d96_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="symbol",
            unique_together={("ticker", "exchange")},
        ),
        migrations.AddIndex(
            model_name="pricedailyfact",
            index=models.Index(
                fields=["symbol", "date"], name="fact_price__symbol__7d6e8f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pricedailyfact",
            index=models.Index(fields=["date"], name="fact_price__date_id_8dee88_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="pricedailyfact",
            unique_together={("symbol", "date")},
        ),
    ]
